// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package com.epam.RPCprotocols.pingpong;

public final class PingPongProto {
  private PingPongProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pingpong_PingPongRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pingpong_PingPongRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pingpong_PingPongReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pingpong_PingPongReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016pingpong.proto\022\010pingpong\"\"\n\017PingPongRe" +
      "quest\022\017\n\007message\030\001 \001(\t\" \n\rPingPongReply\022" +
      "\017\n\007message\030\001 \001(\t2W\n\017PingPongService\022D\n\014S" +
      "endPingPong\022\031.pingpong.PingPongRequest\032\027" +
      ".pingpong.PingPongReply\"\000B1\n\036com.epam.RP" +
      "Cprotocols.pingpongB\rPingPongProtoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pingpong_PingPongRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pingpong_PingPongRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pingpong_PingPongRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_pingpong_PingPongReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pingpong_PingPongReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pingpong_PingPongReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
